// Importing necessary components from Next.js and styled-components
import Document, { Html, Head, Main, NextScript } from "next/document";
import { ServerStyleSheet } from "styled-components";

// Defining a custom Document class by extending Next.js's Document class
export default class MyDocument extends Document {
  // getInitialProps is a static method used to modify the initial properties of the document.
  // This method is executed on the server side.
  static async getInitialProps(ctx) {
    // Create an instance of ServerStyleSheet to handle styled-components styles on the server.
    const sheet = new ServerStyleSheet();
    // Save a reference to the original renderPage function.
    const originalRenderPage = ctx.renderPage;

    try {
      // Modify renderPage to wrap the App component with the ServerStyleSheet.
      // This captures all styles generated by styled-components.
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: (App) => (props) =>
            sheet.collectStyles(<App {...props} />),
        });

      // Call the original getInitialProps of the Document class to get the initial props.
      const initialProps = await Document.getInitialProps(ctx);
      // Return the initial props along with the styles gathered by ServerStyleSheet.
      return {
        ...initialProps,
        styles: [initialProps.styles, sheet.getStyleElement()],
      };
    } finally {
      // Seal the ServerStyleSheet to prevent memory leaks.
      sheet.seal();
    }
  }

  // The render method returns the structure of the HTML document
  render() {
    return (
      // <Html> component to define the language and other attributes of the HTML tag.
      <Html lang="en">
        {/* <Head> component to include elements inside the head tag. */}
        <Head />
        {/* Defines the body of the HTML document. */}
        <body>
          {/* <Main> component, where the app's components will be rendered. */}
          <Main />
          {/* <NextScript> component to include Next.js scripts required for the app to function correctly. */}
          <NextScript />
        </body>
      </Html>
    );
  }
}
